/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as AuthenticatedMeusHorariosRouteImport } from './routes/_authenticated/meus-horarios'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAgendaRouteImport } from './routes/_authenticated/admin.agenda'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminHorariosRouteImport } from './routes/_authenticated/admin.horarios'
import { Route as AuthenticatedAdminPortfolioRouteImport } from './routes/_authenticated/admin.portfolio'
import { Route as AuthenticatedAdminServicosRouteImport } from './routes/_authenticated/admin.servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusHorariosRoute =
  AuthenticatedMeusHorariosRouteImport.update({
    id: '/meus-horarios',
    path: '/meus-horarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAgendaRoute =
  AuthenticatedAdminAgendaRouteImport.update({
    id: '/admin/agenda',
    path: '/admin/agenda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/admin/clientes',
    path: '/admin/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/admin/financeiro',
    path: '/admin/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHorariosRoute =
  AuthenticatedAdminHorariosRouteImport.update({
    id: '/admin/horarios',
    path: '/admin/horarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPortfolioRoute =
  AuthenticatedAdminPortfolioRouteImport.update({
    id: '/admin/portfolio',
    path: '/admin/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicosRoute =
  AuthenticatedAdminServicosRouteImport.update({
    id: '/admin/servicos',
    path: '/admin/servicos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/portfolio': typeof PortfolioRoute
  '/servicos': typeof ServicosRoute
  '/meus-horarios': typeof AuthenticatedMeusHorariosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/horarios': typeof AuthenticatedAdminHorariosRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/portfolio': typeof PortfolioRoute
  '/servicos': typeof ServicosRoute
  '/meus-horarios': typeof AuthenticatedMeusHorariosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/horarios': typeof AuthenticatedAdminHorariosRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/auth': typeof AuthRoute
  '/portfolio': typeof PortfolioRoute
  '/servicos': typeof ServicosRoute
  '/_authenticated/meus-horarios': typeof AuthenticatedMeusHorariosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/horarios': typeof AuthenticatedAdminHorariosRoute
  '/_authenticated/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/_authenticated/admin/servicos': typeof AuthenticatedAdminServicosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/auth'
    | '/portfolio'
    | '/servicos'
    | '/meus-horarios'
    | '/perfil'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/financeiro'
    | '/admin/horarios'
    | '/admin/portfolio'
    | '/admin/servicos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/auth'
    | '/portfolio'
    | '/servicos'
    | '/meus-horarios'
    | '/perfil'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/financeiro'
    | '/admin/horarios'
    | '/admin/portfolio'
    | '/admin/servicos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agendar'
    | '/auth'
    | '/portfolio'
    | '/servicos'
    | '/_authenticated/meus-horarios'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/agenda'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/horarios'
    | '/_authenticated/admin/portfolio'
    | '/_authenticated/admin/servicos'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  AuthRoute: typeof AuthRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-horarios': {
      id: '/_authenticated/meus-horarios'
      path: '/meus-horarios'
      fullPath: '/meus-horarios'
      preLoaderRoute: typeof AuthenticatedMeusHorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agenda': {
      id: '/_authenticated/admin/agenda'
      path: '/admin/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AuthenticatedAdminAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/horarios': {
      id: '/_authenticated/admin/horarios'
      path: '/admin/horarios'
      fullPath: '/admin/horarios'
      preLoaderRoute: typeof AuthenticatedAdminHorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/portfolio': {
      id: '/_authenticated/admin/portfolio'
      path: '/admin/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/servicos': {
      id: '/_authenticated/admin/servicos'
      path: '/admin/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AuthenticatedAdminServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeusHorariosRoute: typeof AuthenticatedMeusHorariosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAdminAgendaRoute: typeof AuthenticatedAdminAgendaRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminHorariosRoute: typeof AuthenticatedAdminHorariosRoute
  AuthenticatedAdminPortfolioRoute: typeof AuthenticatedAdminPortfolioRoute
  AuthenticatedAdminServicosRoute: typeof AuthenticatedAdminServicosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeusHorariosRoute: AuthenticatedMeusHorariosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAdminAgendaRoute: AuthenticatedAdminAgendaRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminHorariosRoute: AuthenticatedAdminHorariosRoute,
  AuthenticatedAdminPortfolioRoute: AuthenticatedAdminPortfolioRoute,
  AuthenticatedAdminServicosRoute: AuthenticatedAdminServicosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgendarRoute: AgendarRoute,
  AuthRoute: AuthRoute,
  PortfolioRoute: PortfolioRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
